// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "docuvault-be/internal/domain/models"

	mock "github.com/stretchr/testify/mock"

	repository "docuvault-be/internal/repository"
)

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, auditLog
func (_m *AuditLogRepository) Create(ctx context.Context, auditLog *models.AuditLog) error {
	ret := _m.Called(ctx, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.AuditLog) error); ok {
		r0 = rf(ctx, auditLog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, filter
func (_m *AuditLogRepository) List(ctx context.Context, filter repository.AuditLogFilter) ([]models.AuditLog, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.AuditLog
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditLogFilter) ([]models.AuditLog, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AuditLogFilter) []models.AuditLog); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AuditLogFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.AuditLogFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MostActiveUsers provides a mock function with given fields: ctx, limit
func (_m *AuditLogRepository) MostActiveUsers(ctx context.Context, limit int) ([]repository.ActiveUserStat, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for MostActiveUsers")
	}

	var r0 []repository.ActiveUserStat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]repository.ActiveUserStat, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []repository.ActiveUserStat); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ActiveUserStat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Recent provides a mock function with given fields: ctx, limit
func (_m *AuditLogRepository) Recent(ctx context.Context, limit int) ([]models.AuditLog, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Recent")
	}

	var r0 []models.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]models.AuditLog, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []models.AuditLog); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
