// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "docuvault-be/internal/domain/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DepartmentRepository is an autogenerated mock type for the DepartmentRepository type
type DepartmentRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, department
func (_m *DepartmentRepository) Create(ctx context.Context, department *models.Department) error {
	ret := _m.Called(ctx, department)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Department) error); ok {
		r0 = rf(ctx, department)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DepartmentRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *DepartmentRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Department, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Department, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Department); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *DepartmentRepository) FindByName(ctx context.Context, name string) (*models.Department, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *models.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Department, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Department); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *DepartmentRepository) List(ctx context.Context) ([]models.Department, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Department, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Department); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, department
func (_m *DepartmentRepository) Update(ctx context.Context, department *models.Department) error {
	ret := _m.Called(ctx, department)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Department) error); ok {
		r0 = rf(ctx, department)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDepartmentRepository creates a new instance of DepartmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepartmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepartmentRepository {
	mock := &DepartmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
