// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	models "docuvault-be/internal/domain/models"

	mock "github.com/stretchr/testify/mock"

	repository "docuvault-be/internal/repository"

	time "time"

	uuid "github.com/google/uuid"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, notification
func (_m *NotificationRepository) Create(ctx context.Context, notification *models.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *NotificationRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *NotificationRepository) List(ctx context.Context, filter repository.NotificationFilter) ([]models.Notification, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Notification
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.NotificationFilter) ([]models.Notification, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.NotificationFilter) []models.Notification); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.NotificationFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.NotificationFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkRead provides a mock function with given fields: ctx, id, userID, readAt
func (_m *NotificationRepository) MarkRead(ctx context.Context, id uuid.UUID, userID uuid.UUID, readAt time.Time) error {
	ret := _m.Called(ctx, id, userID, readAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, userID, readAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkSent provides a mock function with given fields: ctx, id, sentAt
func (_m *NotificationRepository) MarkSent(ctx context.Context, id uuid.UUID, sentAt time.Time) error {
	ret := _m.Called(ctx, id, sentAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkSent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, id, sentAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
