// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "docuvault-be/internal/dto"

	mock "github.com/stretchr/testify/mock"

	service "docuvault-be/internal/service"
)

// AuditLogService is an autogenerated mock type for the AuditLogService type
type AuditLogService struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, request
func (_m *AuditLogService) List(ctx context.Context, request dto.AuditLogListRequest) (dto.PaginatedResponse[dto.AuditLogResponse], error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 dto.PaginatedResponse[dto.AuditLogResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AuditLogListRequest) (dto.PaginatedResponse[dto.AuditLogResponse], error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.AuditLogListRequest) dto.PaginatedResponse[dto.AuditLogResponse]); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.PaginatedResponse[dto.AuditLogResponse])
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.AuditLogListRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Recent provides a mock function with given fields: ctx, limit
func (_m *AuditLogService) Recent(ctx context.Context, limit int) ([]dto.AuditLogResponse, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Recent")
	}

	var r0 []dto.AuditLogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]dto.AuditLogResponse, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []dto.AuditLogResponse); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.AuditLogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Record provides a mock function with given fields: ctx, event
func (_m *AuditLogService) Record(ctx context.Context, event service.AuditEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Record")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.AuditEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLogService creates a new instance of AuditLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogService {
	mock := &AuditLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
