// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "docuvault-be/internal/dto"

	mock "github.com/stretchr/testify/mock"

	service "docuvault-be/internal/service"

	uuid "github.com/google/uuid"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// ForgotPassword provides a mock function with given fields: ctx, request, info
func (_m *AuthService) ForgotPassword(ctx context.Context, request dto.ForgotPasswordRequest, info service.RequestInfo) error {
	ret := _m.Called(ctx, request, info)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ForgotPasswordRequest, service.RequestInfo) error); ok {
		r0 = rf(ctx, request, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: ctx, request, info
func (_m *AuthService) Login(ctx context.Context, request dto.LoginRequest, info service.RequestInfo) (dto.LoginResponse, error) {
	ret := _m.Called(ctx, request, info)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest, service.RequestInfo) (dto.LoginResponse, error)); ok {
		return rf(ctx, request, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest, service.RequestInfo) dto.LoginResponse); ok {
		r0 = rf(ctx, request, info)
	} else {
		r0 = ret.Get(0).(dto.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LoginRequest, service.RequestInfo) error); ok {
		r1 = rf(ctx, request, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, user, info
func (_m *AuthService) Logout(ctx context.Context, user dto.AuthUser, info service.RequestInfo) error {
	ret := _m.Called(ctx, user, info)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AuthUser, service.RequestInfo) error); ok {
		r0 = rf(ctx, user, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Me provides a mock function with given fields: ctx, userID
func (_m *AuthService) Me(ctx context.Context, userID uuid.UUID) (dto.MeResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 dto.MeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.MeResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.MeResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(dto.MeResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, request, info
func (_m *AuthService) Register(ctx context.Context, request dto.RegisterRequest, info service.RequestInfo) (dto.LoginResponse, error) {
	ret := _m.Called(ctx, request, info)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest, service.RequestInfo) (dto.LoginResponse, error)); ok {
		return rf(ctx, request, info)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.RegisterRequest, service.RequestInfo) dto.LoginResponse); ok {
		r0 = rf(ctx, request, info)
	} else {
		r0 = ret.Get(0).(dto.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.RegisterRequest, service.RequestInfo) error); ok {
		r1 = rf(ctx, request, info)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, request, info
func (_m *AuthService) ResetPassword(ctx context.Context, request dto.ResetPasswordRequest, info service.RequestInfo) error {
	ret := _m.Called(ctx, request, info)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ResetPasswordRequest, service.RequestInfo) error); ok {
		r0 = rf(ctx, request, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
