// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "docuvault-be/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CategoryService is an autogenerated mock type for the CategoryService type
type CategoryService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request, createdBy
func (_m *CategoryService) Create(ctx context.Context, request dto.CreateCategoryRequest, createdBy uuid.UUID) (dto.CategoryResponse, error) {
	ret := _m.Called(ctx, request, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCategoryRequest, uuid.UUID) (dto.CategoryResponse, error)); ok {
		return rf(ctx, request, createdBy)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateCategoryRequest, uuid.UUID) dto.CategoryResponse); ok {
		r0 = rf(ctx, request, createdBy)
	} else {
		r0 = ret.Get(0).(dto.CategoryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateCategoryRequest, uuid.UUID) error); ok {
		r1 = rf(ctx, request, createdBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CategoryService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *CategoryService) Get(ctx context.Context, id uuid.UUID) (dto.CategoryResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dto.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.CategoryResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.CategoryResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.CategoryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, request
func (_m *CategoryService) List(ctx context.Context, request dto.CategoryListRequest) (dto.PaginatedResponse[dto.CategoryResponse], error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 dto.PaginatedResponse[dto.CategoryResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CategoryListRequest) (dto.PaginatedResponse[dto.CategoryResponse], error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CategoryListRequest) dto.PaginatedResponse[dto.CategoryResponse]); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.PaginatedResponse[dto.CategoryResponse])
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CategoryListRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, request
func (_m *CategoryService) Update(ctx context.Context, id uuid.UUID, request dto.UpdateCategoryRequest) (dto.CategoryResponse, error) {
	ret := _m.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.CategoryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateCategoryRequest) (dto.CategoryResponse, error)); ok {
		return rf(ctx, id, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateCategoryRequest) dto.CategoryResponse); ok {
		r0 = rf(ctx, id, request)
	} else {
		r0 = ret.Get(0).(dto.CategoryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateCategoryRequest) error); ok {
		r1 = rf(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryService creates a new instance of CategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryService {
	mock := &CategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
