// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "docuvault-be/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DepartmentService is an autogenerated mock type for the DepartmentService type
type DepartmentService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, request
func (_m *DepartmentService) Create(ctx context.Context, request dto.CreateDepartmentRequest) (dto.DepartmentResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 dto.DepartmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateDepartmentRequest) (dto.DepartmentResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateDepartmentRequest) dto.DepartmentResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.DepartmentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateDepartmentRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DepartmentService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: ctx, id
func (_m *DepartmentService) Get(ctx context.Context, id uuid.UUID) (dto.DepartmentResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dto.DepartmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.DepartmentResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.DepartmentResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.DepartmentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *DepartmentService) List(ctx context.Context) ([]dto.DepartmentResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dto.DepartmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dto.DepartmentResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dto.DepartmentResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DepartmentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, request
func (_m *DepartmentService) Update(ctx context.Context, id uuid.UUID, request dto.UpdateDepartmentRequest) (dto.DepartmentResponse, error) {
	ret := _m.Called(ctx, id, request)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.DepartmentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateDepartmentRequest) (dto.DepartmentResponse, error)); ok {
		return rf(ctx, id, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateDepartmentRequest) dto.DepartmentResponse); ok {
		r0 = rf(ctx, id, request)
	} else {
		r0 = ret.Get(0).(dto.DepartmentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateDepartmentRequest) error); ok {
		r1 = rf(ctx, id, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDepartmentService creates a new instance of DepartmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepartmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepartmentService {
	mock := &DepartmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
