// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "docuvault-be/internal/dto"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"

	uuid "github.com/google/uuid"
)

// DocumentService is an autogenerated mock type for the DocumentService type
type DocumentService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id, actor
func (_m *DocumentService) Delete(ctx context.Context, id uuid.UUID, actor dto.AuthUser) error {
	ret := _m.Called(ctx, id, actor)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) error); ok {
		r0 = rf(ctx, id, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Download provides a mock function with given fields: ctx, id, actor
func (_m *DocumentService) Download(ctx context.Context, id uuid.UUID, actor dto.AuthUser) (dto.DownloadDocumentResponse, error) {
	ret := _m.Called(ctx, id, actor)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 dto.DownloadDocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) (dto.DownloadDocumentResponse, error)); ok {
		return rf(ctx, id, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) dto.DownloadDocumentResponse); ok {
		r0 = rf(ctx, id, actor)
	} else {
		r0 = ret.Get(0).(dto.DownloadDocumentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.AuthUser) error); ok {
		r1 = rf(ctx, id, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, id, actor
func (_m *DocumentService) Get(ctx context.Context, id uuid.UUID, actor dto.AuthUser) (dto.DocumentResponse, error) {
	ret := _m.Called(ctx, id, actor)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dto.DocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) (dto.DocumentResponse, error)); ok {
		return rf(ctx, id, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) dto.DocumentResponse); ok {
		r0 = rf(ctx, id, actor)
	} else {
		r0 = ret.Get(0).(dto.DocumentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.AuthUser) error); ok {
		r1 = rf(ctx, id, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HardDelete provides a mock function with given fields: ctx, id, actor
func (_m *DocumentService) HardDelete(ctx context.Context, id uuid.UUID, actor dto.AuthUser) error {
	ret := _m.Called(ctx, id, actor)

	if len(ret) == 0 {
		panic("no return value specified for HardDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) error); ok {
		r0 = rf(ctx, id, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, request, actor
func (_m *DocumentService) List(ctx context.Context, request dto.DocumentListRequest, actor dto.AuthUser) (dto.PaginatedResponse[dto.DocumentResponse], error) {
	ret := _m.Called(ctx, request, actor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 dto.PaginatedResponse[dto.DocumentResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DocumentListRequest, dto.AuthUser) (dto.PaginatedResponse[dto.DocumentResponse], error)); ok {
		return rf(ctx, request, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.DocumentListRequest, dto.AuthUser) dto.PaginatedResponse[dto.DocumentResponse]); ok {
		r0 = rf(ctx, request, actor)
	} else {
		r0 = ret.Get(0).(dto.PaginatedResponse[dto.DocumentResponse])
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.DocumentListRequest, dto.AuthUser) error); ok {
		r1 = rf(ctx, request, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id, actor
func (_m *DocumentService) Restore(ctx context.Context, id uuid.UUID, actor dto.AuthUser) error {
	ret := _m.Called(ctx, id, actor)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) error); ok {
		r0 = rf(ctx, id, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, request, actor
func (_m *DocumentService) Update(ctx context.Context, id uuid.UUID, request dto.UpdateDocumentRequest, actor dto.AuthUser) (dto.DocumentResponse, error) {
	ret := _m.Called(ctx, id, request, actor)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 dto.DocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateDocumentRequest, dto.AuthUser) (dto.DocumentResponse, error)); ok {
		return rf(ctx, id, request, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.UpdateDocumentRequest, dto.AuthUser) dto.DocumentResponse); ok {
		r0 = rf(ctx, id, request, actor)
	} else {
		r0 = ret.Get(0).(dto.DocumentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.UpdateDocumentRequest, dto.AuthUser) error); ok {
		r1 = rf(ctx, id, request, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: ctx, request, fileHeader, actor
func (_m *DocumentService) Upload(ctx context.Context, request dto.UploadDocumentRequest, fileHeader *multipart.FileHeader, actor dto.AuthUser) (dto.DocumentResponse, error) {
	ret := _m.Called(ctx, request, fileHeader, actor)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 dto.DocumentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UploadDocumentRequest, *multipart.FileHeader, dto.AuthUser) (dto.DocumentResponse, error)); ok {
		return rf(ctx, request, fileHeader, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UploadDocumentRequest, *multipart.FileHeader, dto.AuthUser) dto.DocumentResponse); ok {
		r0 = rf(ctx, request, fileHeader, actor)
	} else {
		r0 = ret.Get(0).(dto.DocumentResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UploadDocumentRequest, *multipart.FileHeader, dto.AuthUser) error); ok {
		r1 = rf(ctx, request, fileHeader, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDocumentService creates a new instance of DocumentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentService {
	mock := &DocumentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
