// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "docuvault-be/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, userID, request
func (_m *NotificationService) List(ctx context.Context, userID uuid.UUID, request dto.NotificationListRequest) (dto.PaginatedResponse[dto.NotificationResponse], error) {
	ret := _m.Called(ctx, userID, request)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 dto.PaginatedResponse[dto.NotificationResponse]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.NotificationListRequest) (dto.PaginatedResponse[dto.NotificationResponse], error)); ok {
		return rf(ctx, userID, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.NotificationListRequest) dto.PaginatedResponse[dto.NotificationResponse]); ok {
		r0 = rf(ctx, userID, request)
	} else {
		r0 = ret.Get(0).(dto.PaginatedResponse[dto.NotificationResponse])
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.NotificationListRequest) error); ok {
		r1 = rf(ctx, userID, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkRead provides a mock function with given fields: ctx, id, userID
func (_m *NotificationService) MarkRead(ctx context.Context, id uuid.UUID, userID uuid.UUID) (dto.NotificationResponse, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 dto.NotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (dto.NotificationResponse, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) dto.NotificationResponse); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(dto.NotificationResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkSent provides a mock function with given fields: ctx, id
func (_m *NotificationService) MarkSent(ctx context.Context, id uuid.UUID) (dto.NotificationResponse, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkSent")
	}

	var r0 dto.NotificationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (dto.NotificationResponse, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) dto.NotificationResponse); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(dto.NotificationResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
