// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dto "docuvault-be/internal/dto"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PermissionService is an autogenerated mock type for the PermissionService type
type PermissionService struct {
	mock.Mock
}

// Grant provides a mock function with given fields: ctx, request, actor
func (_m *PermissionService) Grant(ctx context.Context, request dto.GrantPermissionRequest, actor dto.AuthUser) ([]dto.PermissionResponse, error) {
	ret := _m.Called(ctx, request, actor)

	if len(ret) == 0 {
		panic("no return value specified for Grant")
	}

	var r0 []dto.PermissionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GrantPermissionRequest, dto.AuthUser) ([]dto.PermissionResponse, error)); ok {
		return rf(ctx, request, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GrantPermissionRequest, dto.AuthUser) []dto.PermissionResponse); ok {
		r0 = rf(ctx, request, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PermissionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GrantPermissionRequest, dto.AuthUser) error); ok {
		r1 = rf(ctx, request, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByDocument provides a mock function with given fields: ctx, documentID, actor
func (_m *PermissionService) ListByDocument(ctx context.Context, documentID uuid.UUID, actor dto.AuthUser) ([]dto.PermissionResponse, error) {
	ret := _m.Called(ctx, documentID, actor)

	if len(ret) == 0 {
		panic("no return value specified for ListByDocument")
	}

	var r0 []dto.PermissionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) ([]dto.PermissionResponse, error)); ok {
		return rf(ctx, documentID, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) []dto.PermissionResponse); ok {
		r0 = rf(ctx, documentID, actor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.PermissionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.AuthUser) error); ok {
		r1 = rf(ctx, documentID, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Revoke provides a mock function with given fields: ctx, id, actor
func (_m *PermissionService) Revoke(ctx context.Context, id uuid.UUID, actor dto.AuthUser) error {
	ret := _m.Called(ctx, id, actor)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.AuthUser) error); ok {
		r0 = rf(ctx, id, actor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPermissionService creates a new instance of PermissionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPermissionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PermissionService {
	mock := &PermissionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
